new subcommand find

diff --git a/brawlhalla b/brawlhalla
--- a/brawlhalla
+++ b/brawlhalla
@@ -1,6 +1,8 @@
 #!/bin/bash
 
-### HELP STUFF ###
+#######################################################################
+################################ UTILS ################################
+#######################################################################
 
 prog_name=$(basename "$0")
 
@@ -20,7 +22,9 @@ ask_confirm() {
     done
 }
 
-### SUBCOMMAND profiles ###
+#####################################################################################
+################################ SUBCOMMAND profiles ################################
+#####################################################################################
 
 PROFILES_DIR="$HOME/.brawlhalla/profiles"
 ACTIVE_PROFILE_DIR="$(wslpath "$(wslvar APPDATA)")/BrawlhallaAir/Local Store/"
@@ -28,7 +32,7 @@ ACTIVE_PROFILE_DIR="$(wslpath "$(wslvar APPDATA)")/BrawlhallaAir/Local Store/"
 sub_profiles_list() {
     for file in "$PROFILES_DIR"/*; do
         if [ -d "$file" ]; then
-            echo "$(basename "$file")"
+            basename "$file"
         fi
     done
 }
@@ -105,7 +109,9 @@ sub_profiles() {
     esac
 }
 
-### SUBCOMMAND track ###
+##################################################################################
+################################ SUBCOMMAND track ################################
+##################################################################################
 
 TRACK_DIR="$HOME/.brawlhalla/tracking"
 TRACK_RANDOM_FILE="$HOME/.brawlhalla/tracking/random.txt"
@@ -148,7 +154,41 @@ sub_track() {
     esac
 }
 
-### MAIN ###
+#################################################################################
+################################ SUBCOMMAND find ################################
+#################################################################################
+
+WEAPON_LIST=";sword;katars;blasters;bow;gauntlets;scythe;hammer;greatsword;spear;orb;axe;lance;chakram;"
+declare -A WEAPONS_TO_LEGEND=( ["hammer_sword"]="bodvar" ["blasters_hammer"]="cassidy" ["lance_spear"]="orion" ["lance_blasters"]="lord vraxx" ["hammer_spear"]="gnash" ["spear_katars"]="queen nai" ["sword_spear"]="hattori" ["lance_sword"]="sir roland" ["hammer_lance"]="scarlet" ["sword_blasters"]="thatch" ["blasters_spear"]="ada" ["hammer_katars"]="sentinel" ["katars_blasters"]="lucien" ["axe_hammer"]="teros" ["axe_spear"]="brynn" ["katars_sword"]="asuri" ["axe_blasters"]="barraza" ["bow_katars"]="ember" ["bow_axe"]="azoth" ["bow_sword"]="koji" ["axe_lance"]="ulgrim" ["bow_blasters"]="diana" ["axe_sword"]="jhala" ["gauntlets_hammer"]="kor" ["gauntlets_spear"]="wu shang" ["gauntlets_sword"]="val" ["katars_axe"]="ragnir" ["blasters_gauntlets"]="cross" ["scythe_spear"]="mirage" ["scythe_blasters"]="nix" ["scythe_gauntlets"]="mordex" ["bow_hammer"]="yumiko" ["lance_scythe"]="artemis" ["gauntlets_katars"]="caspian" ["cannon_sword"]="sidra" ["cannon_axe"]="xull" ["spear_bow"]="kaya" ["cannon_blasters"]="isaiah" ["sword_scythe"]="jiro" ["katars_cannon"]="lin fei" ["gauntlets_bow"]="zariel" ["gauntlets_axe"]="rayman" ["spear_orb"]="dusk" ["scythe_orb"]="fait" ["hammer_orb"]="thor" ["gauntlets_orb"]="petra" ["lance_bow"]="vector" ["axe_scythe"]="volkov" ["gauntlets_cannon"]="onyx" ["sword_greatsword"]="jaeyun" ["katars_greatsword"]="mako" ["hammer_greatsword"]="magyar" ["blasters_orb"]="reno" ["bow_scythe"]="munin" ["spear_greatsword"]="arcadia" ["sword_orb"]="ezio" ["boots_gauntlets"]="tezca" ["boots_lance"]="thea" ["boots_orb"]="redraptor" ["katars_scythe"]="loki" ["spear_cannon"]="seven" ["boots_blasters"]="vivi" ["axe_greatsword"]="imugi" ["hammer_boots"]="king zuva" ["chakram_sword"]="priya" ["sword_hammer"]="bodvar" ["hammer_blasters"]="cassidy" ["spear_lance"]="orion" ["blasters_lance"]="lord vraxx" ["spear_hammer"]="gnash" ["katars_spear"]="queen nai" ["spear_sword"]="hattori" ["sword_lance"]="sir roland" ["lance_hammer"]="scarlet" ["blasters_sword"]="thatch" ["spear_blasters"]="ada" ["katars_hammer"]="sentinel" ["blasters_katars"]="lucien" ["hammer_axe"]="teros" ["spear_axe"]="brynn" ["sword_katars"]="asuri" ["blasters_axe"]="barraza" ["katars_bow"]="ember" ["axe_bow"]="azoth" ["sword_bow"]="koji" ["lance_axe"]="ulgrim" ["blasters_bow"]="diana" ["sword_axe"]="jhala" ["hammer_gauntlets"]="kor" ["spear_gauntlets"]="wu shang" ["sword_gauntlets"]="val" ["axe_katars"]="ragnir" ["gauntlets_blasters"]="cross" ["spear_scythe"]="mirage" ["blasters_scythe"]="nix" ["gauntlets_scythe"]="mordex" ["hammer_bow"]="yumiko" ["scythe_lance"]="artemis" ["katars_gauntlets"]="caspian" ["sword_cannon"]="sidra" ["axe_cannon"]="xull" ["bow_spear"]="kaya" ["blasters_cannon"]="isaiah" ["scythe_sword"]="jiro" ["cannon_katars"]="lin fei" ["bow_gauntlets"]="zariel" ["axe_gauntlets"]="rayman" ["orb_spear"]="dusk" ["orb_scythe"]="fait" ["orb_hammer"]="thor" ["orb_gauntlets"]="petra" ["bow_lance"]="vector" ["scythe_axe"]="volkov" ["cannon_gauntlets"]="onyx" ["greatsword_sword"]="jaeyun" ["greatsword_katars"]="mako" ["greatsword_hammer"]="magyar" ["orb_blasters"]="reno" ["scythe_bow"]="munin" ["greatsword_spear"]="arcadia" ["orb_sword"]="ezio" ["gauntlets_boots"]="tezca" ["lance_boots"]="thea" ["orb_boots"]="redraptor" ["scythe_katars"]="loki" ["cannon_spear"]="seven" ["blasters_boots"]="vivi" ["greatsword_axe"]="imugi" ["boots_hammer"]="king zuva" ["sword_chakram"]="priya")
+
+sub_find_help() {
+    echo "Usage: $prog_name find <weapon1> <weapon2>"
+    echo ""
+    echo "tool for finding a legend with a specific weapon combination"
+}
+
+sub_find() {
+    weapon1="$1"
+    weapon2="$2"
+    if [[ $WEAPON_LIST != *";$weapon1;"* ]]; then
+        echo "Error: '$weapon1' is not a valid weapon name." >&2
+        exit 1
+    fi
+    if [[ $WEAPON_LIST != *";$weapon2;"* ]]; then
+        echo "Error: '$weapon2' is not a valid weapon name." >&2
+        exit 1
+    fi
+    legend_name="${WEAPONS_TO_LEGEND["$weapon1"_"$weapon2"]}"
+    if [ -z "$legend_name" ]; then
+        echo "No legend found for weapons $weapon1 and $weapon2."
+    else
+        echo "Legend for weapons $weapon1 and $weapon2 is $legend_name."
+    fi
+}
+
+######################################################################
+################################ MAIN ################################
+######################################################################
 
 sub_help() {
     echo "Usage: $prog_name <subcommand>"
@@ -169,6 +209,10 @@ case "$subcommand" in
     sub_"${subcommand}" "$@"
     ;;
 "track")
+    shift
+    sub_"${subcommand}" "$@"
+    ;;
+"find")
     shift
     sub_"${subcommand}" "$@"
     ;;
